wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.0
    framework: huggingface
    huggingface_version: 4.35.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1701544743.472372
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 105
      3:
      - 23
      4: 3.9.18
      5: 0.16.0
      6: 4.35.2
      8:
      - 1
      - 5
      13: darwin-x86_64
