wandb_version: 1

epochs:
  desc: null
  value: 2
batch_size:
  desc: null
  value: 128
lr:
  desc: null
  value: 0.0001
dropout:
  desc: null
  value: 0.5
slice_size:
  desc: null
  value: 10000
valid_pct:
  desc: null
  value: 0.2
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.0
    framework: huggingface
    huggingface_version: 4.35.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1701516829.369547
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 105
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 105
      3:
      - 2
      - 16
      - 23
      4: 3.9.18
      5: 0.16.0
      6: 4.35.2
      8:
      - 1
      - 5
      13: darwin-x86_64
